{*
* 2006-2021 THECON SRL
*
* NOTICE OF LICENSE
*
* DISCLAIMER
*
* YOU ARE NOT ALLOWED TO REDISTRIBUTE OR RESELL THIS FILE OR ANY OTHER FILE
* USED BY THIS MODULE.
*
* @author    THECON SRL <contact@thecon.ro>
* @copyright 2006-2021 THECON SRL
* @license   Commercial
*}

{addJsDef THSCROLL_SPEED=$THSCROLL_SPEED|escape:'htmlall':'UTF-8'}
{addJsDef THSCROLL_SHOW_AFTER=$THSCROLL_SHOW_AFTER|escape:'htmlall':'UTF-8'}
